[package]
name = "firecore-audio"
version = "0.2.0"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

[features]
default = []
file = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }